apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"rfp-backend","namespace":"ahmed"},"spec":{"ports":[{"port":8420,"targetPort":8420}],"selector":{"app":"rfp-backend"}}}
  creationTimestamp: "2026-09-26T05:29:14Z"
  name: rfp-backend
  namespace: ahmed
  resourceVersion: "830774"
  uid: 669deb92-46df-41d6-a69f-354ed88fd6a9
spec:
  clusterIP: 10.43.41.28
  clusterIPs:
  - 10.43.41.28
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 8420
    protocol: TCP
    targetPort: 8420
  selector:
    app: rfp-backend
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
