apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"k2-vllm","namespace":"ahmed"},"spec":{"ports":[{"port":8000,"targetPort":8000}],"selector":{"app":"k2-vllm"}}}
  creationTimestamp: "2026-09-26T05:13:42Z"
  name: k2-vllm
  namespace: ahmed
  resourceVersion: "830025"
  uid: 70833fb5-4f73-4fdf-ba09-e797b1e141c6
spec:
  clusterIP: 10.43.252.109
  clusterIPs:
  - 10.43.252.109
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: k2-vllm
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
