apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"grafana","namespace":"ahmed"},"spec":{"ports":[{"port":3000,"targetPort":3000}],"selector":{"app":"grafana"}}}
  creationTimestamp: "2026-09-26T05:28:03Z"
  name: grafana
  namespace: ahmed
  resourceVersion: "830741"
  uid: c526f407-ab47-4347-bd93-73c692cc1255
spec:
  clusterIP: 10.43.114.137
  clusterIPs:
  - 10.43.114.137
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: grafana
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
