apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"rfp-frontend","namespace":"ahmed"},"spec":{"ports":[{"port":80,"targetPort":80}],"selector":{"app":"rfp-frontend"}}}
  creationTimestamp: "2026-09-26T05:29:14Z"
  name: rfp-frontend
  namespace: ahmed
  resourceVersion: "830778"
  uid: 55be12b8-d742-44ec-bbf5-49f5567e7c36
spec:
  clusterIP: 10.43.184.82
  clusterIPs:
  - 10.43.184.82
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: rfp-frontend
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
